#!/usr/bin/env python

import threading
import thread

import pygtk
pygtk.require('2.0')
import gtk
import gobject
gobject.threads_init()

import os
import re
import shutil
import sys
import urllib
from urllib import FancyURLopener

from datetime import datetime
from datetime import time
from datetime import timedelta
from time import sleep

class Bijin:
    version = '0.9.6'
    url_template = 'http://www.clockm.com/tw/widget/img/clk/hour/%H%M.jpg'
    source_urls = {
        0: {
            'title': 'ClockM - small',
            'url': 'http://www.clockm.com/tw/widget/img/clk/hour/%H%M.jpg',
            'width': 160,
            'height': 240,
        },
        1: {
            'title': 'ClockM - Big',
            'url': 'http://www.clockm.com/tw/img/clk/hour/%H%M.jpg',
            'width': 399,
            'height': 600,
        },
        #2: {
        #    'title': 'Bijin Tokei - Big',
        #    'url': 'http://bijint.com/jp/tokei_images/%H%M.jpg',
        #    'width': 590,
        #    'height': 450,
        #}
    }

    source_selected = 0
    last_source_selected = source_selected

    cache_dir = "~/.bijinclock/caches"
    is_fetch_next = True
    window = None
    clock_image = None
    is_exit = False
    last_time = None

    def __init__(self):
        self.init_cache_dir()

        self.window = gtk.Window(gtk.WINDOW_TOPLEVEL)
        self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_DIALOG)
        self.window.set_title('loading...')
        self.window.set_size_request(160, 240)
        self.window.set_resizable(False)

        ui_source_selector = """<ui><popup name="Popup">"""

        for source_id in self.source_urls:
            ui_source_selector += """<menuitem name="source%s" action="source%s" />""" % (source_id, source_id)

        ui_source_selector += """</popup></ui>"""

        ui = """<ui>
            <popup name="Popup">
                <separator />
                <menuitem name="AlwaysOnTop" action="AlwaysOnTop" />
                <separator />
                <menuitem name="About" action="About" />
                <separator />
                <menuitem name="Quit" action="Quit" />
            </popup>
        </ui>"""



        self.ui_manager = gtk.UIManager()
        accel_group = self.ui_manager.get_accel_group()
        self.window.add_accel_group(accel_group)
        action_group = gtk.ActionGroup("Bijin Clock Action Group")
        action_group.add_actions(
            [
                ("Configure", None, "_Configure", None,
                    None, self.show_config_window
                ),
                ("About", None, "_About", None,
                    None, self.show_about_window
                ),
                ("Quit", None, "_Quit", None,
                    None, lambda w: self.window.destroy()
                ),
            ]
        )
        action_group.add_toggle_actions(
            [
                (
                    # action name
                    'AlwaysOnTop',
                    # stock id
                    None,
                    # label
                    'Always on _top',
                    # accelerator
                    None,
                    # tooltip
                    None,
                    # callback
                    self.toggle_always_on_top,
                    # active flag
                    False
                )
            ]
        )

        select_source_actions = []
        for source_id in self.source_urls:
             select_source_actions += [(
                "source%s" % source_id,
                None,
                self.source_urls[source_id]['title'],
                None,
                None,
                source_id
            )]

        action_group.add_radio_actions(select_source_actions, self.source_selected, self.on_select_source)

        self.ui_manager.insert_action_group(action_group, 0)
        self.ui_manager.add_ui_from_string(ui_source_selector)
        self.ui_manager.add_ui_from_string(ui)
        self.popup = self.ui_manager.get_widget("/Popup")

        event_box = gtk.EventBox()
        self.window.add(event_box)

        self.clock_image = gtk.Image()
        event_box.add(self.clock_image)

        self.window.show_all()

        event_box.connect("button-press-event", self.on_button_press_event)
        self.window.connect("delete_event", self.onMainDelete)
        self.window.connect("destroy", self.onMainDestroy)

    def init_cache_dir(self):
        self.cache_dir = os.path.expanduser(self.cache_dir)
        try:
            shutil.rmtree(self.cache_dir)
        except:
            pass

        os.makedirs(self.cache_dir)

    def main(self):
        interval_thread = IntervalThread(self)
        interval_thread.start()

        gtk.main()

    def on_button_press_event(self, widget, event):
        self.popup.popup(None, None, None, event.button, event.time)

    def toggle_always_on_top(self, action):
        self.window.set_keep_above(action.get_active())

    def on_select_source(self, current, data):
        self.source_selected = current.get_current_value()

    def show_about_window(self, data):

        window = gtk.Window(gtk.WINDOW_TOPLEVEL)
        window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_UTILITY)
        window.set_resizable(False)
        window.set_title('Bijin Clock')
        window.set_border_width(10)
        window.set_modal(True)
        window.set_property('skip-taskbar-hint', True)
        window.set_transient_for(self.window)
        window.set_position(gtk.WIN_POS_CENTER_ON_PARENT)

        vbox = gtk.VBox(False, 5)
        window.add(vbox)

        label = gtk.Label("Bijin Clock v%s" % self.version)
        vbox.add(label)

        label = gtk.Label("https://github.com/adhisimon/bijinclock")
        vbox.add(label)

        label = gtk.Label("(c) gua@adhisimon.or.id 2011")
        vbox.add(label)

        label = gtk.Label("")
        vbox.add(label)

        label = gtk.Label("Special thanks to:")
        vbox.add(label)

        label = gtk.Label("http://www.clockm.com/")
        vbox.add(label)

        label = gtk.Label("for providing great photos")
        vbox.add(label)

        window.show_all()

    def url_to_show(self, hour = None, minute = None):
        if not hour:
            time_to_show = datetime.now()
        else:
            time_to_show = time(hour = hour, minute = minute)

        #return time_to_show.strftime(self.url_template)
        return time_to_show.strftime(self.source_urls[self.source_selected]['url'])

    def url_to_show_next(self):
        now = datetime.now()
        next_minute = timedelta(minutes = 1) + now

        return self.url_to_show(next_minute.hour, next_minute.minute)

    def replace_image(self, filename):
        self.window.set_size_request(
            self.source_urls[self.source_selected]['width'],
            self.source_urls[self.source_selected]['height']
        )
        self.clock_image.set_from_file(filename)
        self.last_source_selected = self.source_selected
        os.remove(filename)

    def do_show(self):
        now = datetime.now()

        if (self.last_source_selected == self.source_selected) and self.last_time and (
            self.last_time.hour == now.hour
            and self.last_time.minute == now.minute
        ):
            return

        self.last_time = now

        url = self.url_to_show()

        filename = self.do_fetch(url)
        gobject.idle_add(self.window.set_title, 'Bijin Clock')
        gobject.idle_add(self.replace_image, filename)

        self.do_fetch_next()

    def sanitized_url(self, url):
        sanitized_url = re.sub(r'''\W''', '.', url)
        return sanitized_url

    def do_fetch(self, url):
        sanitized_url = self.sanitized_url(url)
        cache_file = self.cache_dir + '/' + sanitized_url

        if not os.path.exists(cache_file):
            print datetime.now(), 'downloading %s' % url

            myurlopener = MyUrlOpener()
            myurlopener.retrieve(url, cache_file)
            print datetime.now(), '%s has been downloaded' % url

        return cache_file

    def do_fetch_next(self):
        url= self.url_to_show_next()
        self.do_fetch(url)

    def show_config_window(self, data = None):
        window = gtk.Window(gtk.WINDOW_TOPLEVEL)
        window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_UTILITY)
        window.set_resizable(False)
        window.set_title('Bijin Clock Configuration')
        window.set_border_width(10)
        window.set_modal(True)
        window.set_property('skip-taskbar-hint', True)
        window.set_transient_for(self.window)
        window.set_position(gtk.WIN_POS_CENTER_ON_PARENT)

        vbox = gtk.VBox(False, 5)
        window.add(vbox)

        label = gtk.Label("Not implemented yet")
        vbox.add(label)

        window.show_all()

    def onMainDelete(self, widget, event, data = None):
        return False

    def onMainDestroy(self, widget, data = None):
        gtk.main_quit()
        print "Terminating..."
        self.is_exit = True

class IntervalThread(threading.Thread):
    caller = None

    def __init__(self, caller):
        super(IntervalThread, self).__init__()
        self.caller = caller

    def run(self):
        caller = self.caller

        while not caller.is_exit:
            caller.do_show()

            now = datetime.now()
            next_minute = timedelta(minutes = 1) + now
            next_minute = next_minute.replace(second = 0, microsecond = 0)
            sleep_time = next_minute - now

            sleep(min(2, sleep_time.seconds + 1))

class MyUrlOpener(FancyURLopener):
    version = 'BijinClock http://adhisimon.or.id/bijinclock'

if __name__ == '__main__':
    bijin = Bijin()
    bijin.main()
